
--CREA PARAMETROS PARA LA ENTIDAD D_TESTSQLSERVER EN params_des
DELETE FROM params_des WHERE ENTIDAD= 'D_TESTSQLSERVER';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_TESTSQLSERVER','VAL_RUTA','/home/nae108834/sqlservertest','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_TESTSQLSERVER','VAL_ESQUEMA','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_TESTSQLSERVER','VAL_TABLA','otc_t_v_sqlservertest','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_TESTSQLSERVER','VAL_DATABASE','telefonica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_TESTSQLSERVER','VAL_USUARIO','userdas','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_TESTSQLSERVER','VAL_PASSWORD','CM3wm#$9iiHr','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_TESTSQLSERVER','VAL_ESQUEMA_SQLSERVER','dbo','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_TESTSQLSERVER','VAL_TABLA_SQLSERVER','HEC_INTERCONEXION','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_TESTSQLSERVER','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','0');
SELECT * FROM params_des WHERE ENTIDAD='D_TESTSQLSERVER' ORDER BY PARAMETRO;
