+------------------------------+-----------+----------------------------------+-------+----------+
| ENTIDAD                      | PARAMETRO | VALOR                            | ORDEN | AMBIENTE |
+------------------------------+-----------+----------------------------------+-------+----------+
| D_OTC_T_B2B_PARQUE_FACTURACION | RUTA      | /RGenerator/reportes/tablero_b2b |     0 |        1 |
| D_OTC_T_B2B_PARQUE_FACTURACION | ESQUEMA   | db_reportes                      |     0 |        1 |
| D_OTC_T_B2B_PARQUE_FACTURACION | COLA_HIVE | capa_semantica                   |     0 |        1 |
+------------------------------+-----------+----------------------------------+-------+----------+

--PARAMETROS PARA LA ENTIDAD D_OTC_T_B2B_PARQUE_FACTURACION
DELETE FROM params_des WHERE entidad='D_OTC_T_B2B_PARQUE_FACTURACION';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_B2B_PARQUE_FACTURACION','RUTA','/home/nae108834/RGenerator/reportes/tablero_b2b','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_B2B_PARQUE_FACTURACION','ESQUEMA','db_desarrollo2021','0','0'); --db_reportes
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_OTC_T_B2B_PARQUE_FACTURACION','COLA_HIVE','capa_semantica','0','0');
SELECT * FROM params_des WHERE ENTIDAD='D_OTC_T_B2B_PARQUE_FACTURACION';

--PARAMETROS PARA LA ENTIDAD D_BIRPIOTM2MTTFAPN0020
DELETE FROM params_des WHERE entidad='D_BIRPIOTM2MTTFAPN0020';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','SHELL','/home/nae108834/RGenerator/reportes/IOT_M2M_TRAFICO_APN/bin/OTC_T_OUT_IP.sh','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_RUTA','/home/nae108834/RGenerator/reportes/IOT_M2M_TRAFICO_APN','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','PARAM1_FECHA_EJEC','date_format(sysdate(),''%Y%m%d'')','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','ETAPA','1','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','QUEUE','reportes','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDUSER','rdb_reportes','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDPASS','TelfEcu2017','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDHOST','proxfulldg1.otecel.com.ec','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDPORT','7594','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDDB','tomstby.otecel.com.ec','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDTABLE','tmp_otc_t_ip','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','HIVEDB','db_desarrollo2021','0','0'); --db_temporales
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TIPO_CARGA','overwrite','0','0'); 
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_MASTER','local','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_DRIVER_MEMORY','8G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_EXECUTOR_MEMORY','8G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_NUM_EXECUTORS','4','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_NUM_EXECUTOR_CORES','4','0','0');
SELECT * FROM params_des WHERE ENTIDAD='D_BIRPIOTM2MTTFAPN0020';
